import React,{useEffect,useMemo,useRef,useState}from"react";
import{MapContainer,TileLayer,Marker,Circle,Popup,useMap}from"react-leaflet";import L from"leaflet";
import{AlertTriangle,Bell,BookOpen,CheckCircle2,ChevronRight,ClipboardList,HeartHandshake,Home,LifeBuoy,Menu,Phone,Plus,ShieldCheck,Siren,Users,X,MapPin,Radio,Settings,Navigation}from"lucide-react";
const api=async(path,opt={})=>{const r=await fetch(path,{headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok)throw Error(d.message||"Request failed");return d};
const resources=[{title:"Personal safety",text:"Stay with trusted adults, avoid isolated places, and tell an adult when something feels unsafe."},{title:"Online safety",text:"Keep passwords private, avoid sharing personal details, and report suspicious messages or accounts."},{title:"Bullying support",text:"Save evidence, move to a safe place, and tell a parent, guardian, teacher, or trusted adult."},{title:"Emergency awareness",text:"Know your trusted contacts and local emergency number. In an emergency, contact appropriate local services."}];
const childIcon=new L.DivIcon({className:"child-marker",html:`<div class="marker-pin">●</div>`,iconSize:[30,30],iconAnchor:[15,15]});
function Center({pos}){const map=useMap();useEffect(()=>{if(pos)map.setView(pos,Math.max(15,map.getZoom()))},[pos,map]);return null}
function time(v){return v?new Date(v).toLocaleTimeString():"Waiting…"}
export default function App(){const[page,setPage]=useState("dashboard"),[open,setOpen]=useState(false),[reports,setReports]=useState([]),[contacts,setContacts]=useState([]),[child,setChild]=useState(null),[geo,setGeo]=useState(null),[alerts,setAlerts]=useState([]),[tracking,setTracking]=useState(false),[permission,setPermission]=useState("Not started"),[toast,setToast]=useState(""),[reportOpen,setReportOpen]=useState(false),[contactOpen,setContactOpen]=useState(false),[sosOpen,setSosOpen]=useState(false),[radius,setRadius]=useState(500),watch=useRef(null),last=useRef(0),lastAlert=useRef(null);
const load=async()=>{try{const[d,r,c]=await Promise.all([api("/api/state"),api("/api/reports"),api("/api/contacts")]);setChild(d.child);setGeo(d.geofence);setAlerts(d.alerts||[]);setReports(r.reports);setContacts(c.contacts);setRadius(d.geofence.radiusMeters)}catch{}};useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),3500);return()=>clearTimeout(t)},[toast]);
const pos=useMemo(()=>child?[child.latitude,child.longitude]:[13.0827,80.2707],[child]);
const send=async(c)=>{if(Date.now()-last.current<2200)return;last.current=Date.now();try{const d=await api("/api/location",{method:"POST",body:JSON.stringify({latitude:c.latitude,longitude:c.longitude,accuracy:c.accuracy,speed:c.speed||0})});setChild(d.child);setGeo(d.geofence);if(d.alert&&d.alert.id!==lastAlert.current){lastAlert.current=d.alert.id;setAlerts(a=>[d.alert,...a]);setToast("Safe-boundary alert generated");if("Notification"in window&&Notification.permission==="granted")new Notification("Child Safety Alert",{body:d.alert.message})}}catch(e){setToast(e.message)}};
const start=()=>{if(!navigator.geolocation)return setPermission("Geolocation is not supported");if("Notification"in window&&Notification.permission==="default")Notification.requestPermission().catch(()=>{});setPermission("Requesting permission…");watch.current=navigator.geolocation.watchPosition(p=>{setTracking(true);setPermission("Location permission granted");send(p.coords)},e=>{setTracking(false);setPermission(e.message||"Permission denied")},{enableHighAccuracy:true,maximumAge:3000,timeout:10000})};
const stop=()=>{if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;setTracking(false);setPermission("Tracking paused")};
const saveGeo=async()=>{if(!child)return;const d=await api("/api/geofence",{method:"POST",body:JSON.stringify({latitude:child.latitude,longitude:child.longitude,radiusMeters:Number(radius),enabled:true})});setGeo(d);setToast("Safe boundary updated")};
const test=async()=>{const d=await api("/api/test-alert",{method:"POST"});setAlerts(a=>[d.alert,...a]);setToast(d.external?.sent?"Test SMS sent":"Test alert created — SMS not configured")};
const sos=async()=>{await api("/api/sos",{method:"POST",body:JSON.stringify({source:"guardian-dashboard",timestamp:new Date().toISOString(),location:child?{latitude:child.latitude,longitude:child.longitude}:null})}).catch(()=>{});setSosOpen(false);setToast("SOS workflow activated")};
const report=async f=>{try{const d=await api("/api/reports",{method:"POST",body:JSON.stringify(f)});setReports(r=>[d.report,...r]);setReportOpen(false);setToast("Safety report submitted")}catch(e){setToast(e.message)}};
const addContact=async f=>{try{const d=await api("/api/contacts",{method:"POST",body:JSON.stringify(f)});setContacts(c=>[...c,d.contact]);setContactOpen(false);setToast("Trusted contact added")}catch(e){setToast(e.message)}};
function nav(p){setPage(p);setOpen(false)}
return <div className="app"><header className="top"><button className="brand" onClick={()=>nav("dashboard")}><span className="logo"><ShieldCheck/></span><span><b>SafeNest</b><small>Child Safety Platform</small></span></button><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div className={`live-pill ${tracking?"on":""}`}><i/> {tracking?"LIVE TRACKING":"MONITORING READY"}</div></header>
<aside className={`sidebar ${open?"open":""}`}><nav><Nav icon={<Home/>} t="Dashboard" a={page==="dashboard"} on={()=>nav("dashboard")}/><Nav icon={<Radio/>} t="Live Tracking" a={page==="tracking"} on={()=>nav("tracking")}/><Nav icon={<ClipboardList/>} t="Safety Reports" a={page==="reports"} on={()=>nav("reports")}/><Nav icon={<Users/>} t="Trusted Contacts" a={page==="contacts"} on={()=>nav("contacts")}/><Nav icon={<BookOpen/>} t="Safety Resources" a={page==="resources"} on={()=>nav("resources")}/></nav><div className="side-bottom"><div className="mini"><ShieldCheck/><span><b>Safety first</b><small>Protected guardian workflow</small></span></div><button className="sos-side" onClick={()=>setSosOpen(true)}><Siren/> SOS / Get Help</button></div></aside>
<main className="main">{page==="dashboard"&&<Dashboard child={child} tracking={tracking} reports={reports} contacts={contacts} alerts={alerts} onTrack={()=>nav("tracking")} onReport={()=>setReportOpen(true)} onSOS={()=>setSosOpen(true)} onContacts={()=>nav("contacts")}/>} {page==="tracking"&&<Tracking child={child} geo={geo} alerts={alerts} tracking={tracking} permission={permission} radius={radius} setRadius={setRadius} start={start} stop={stop} saveGeo={saveGeo} test={test}/>} {page==="reports"&&<Reports reports={reports} newReport={()=>setReportOpen(true)}/>} {page==="contacts"&&<Contacts contacts={contacts} add={()=>setContactOpen(true)}/>} {page==="resources"&&<Resources/>}</main>
{reportOpen&&<ReportModal close={()=>setReportOpen(false)} submit={report}/>} {contactOpen&&<ContactModal close={()=>setContactOpen(false)} submit={addContact}/>} {sosOpen&&<SOS close={()=>setSosOpen(false)} confirm={sos} contacts={contacts}/>} {toast&&<div className="toast"><CheckCircle2/> {toast}</div>}</div>}
function Nav({icon,t,a,on}){return <button className={`nav ${a?"active":""}`} onClick={on}>{icon}<span>{t}</span></button>}
function Dashboard({child,tracking,reports,contacts,alerts,onTrack,onReport,onSOS,onContacts}){return <><section className="hero"><div><span className="eyebrow">GUARDIAN CONTROL CENTER</span><h1>A safer place starts with staying connected.</h1><p>Monitor your child's location, create a safe boundary, respond to alerts, and reach trusted contacts from one place.</p><div className="actions"><button className="btn primary" onClick={onTrack}><Navigation/> Open live tracking</button><button className="btn emergency" onClick={onSOS}><Siren/> SOS / Get Help</button></div></div><div className="hero-art"><ShieldCheck size={100}/><span>LIVE<br/>SAFETY</span></div></section><section className="stats"><Stat icon={<MapPin/>} value={tracking?"LIVE":"READY"} label="Location monitoring"/><Stat icon={<ShieldCheck/>} value={child?.status==="Safe"?"SAFE":"ALERT"} label="Child status"/><Stat icon={<Bell/>} value={alerts.length} label="Safety alerts"/><Stat icon={<Users/>} value={contacts.length} label="Trusted contacts"/></section><div className="two"><section className="panel"><Head title="Child status" sub="Current monitoring state"/><div className={`child-card ${child?.status==="Safe"?"safe":"danger"}`}><div className="avatar">{child?.name?.[0]||"A"}</div><div className="child-info"><h3>{child?.name||"Aarav"}</h3><span>Age {child?.age||10} · {child?.status||"Waiting"}</span><small>Last update: {time(child?.updatedAt)}</small></div><button className="btn primary" onClick={onTrack}>View map</button></div></section><section className="panel"><Head title="Quick actions" sub="Common safety tools"/><Quick icon={<ClipboardList/>} t="Report a concern" s="Create a safety report" on={onReport}/><Quick icon={<Users/>} t="Trusted contacts" s="People who can help" on={onContacts}/><Quick icon={<Radio/>} t="Live tracking" s="Open location & geofence" on={onTrack}/></section></div><section className="panel"><Head title="Recent safety activity" sub="Latest alerts from the connected system"/><Activity alerts={alerts.slice(0,4)}/></section></>}
function Tracking({child,geo,alerts,tracking,permission,radius,setRadius,start,stop,saveGeo,test}){const pos=child?[child.latitude,child.longitude]:[13.0827,80.2707];return <><PageTitle eyebrow="LIVE SAFETY MONITORING" title="Live location & safe boundary" text="Track the child's current position and automatically detect when they leave the defined safe area." action={<button className={`btn ${tracking?"danger":"primary"}`} onClick={tracking?stop:start}>{tracking?"Stop live tracking":"Start live tracking"}</button>}/><div className="tracking-grid"><section className="map-panel"><div className="map-top"><div><b>{child?.name||"Aarav"}</b><span>{child?.status||"Waiting"} · Updated {time(child?.updatedAt)}</span></div><div className={`map-status ${tracking?"active":""}`}><i/> {tracking?"GPS CONNECTED":"GPS PAUSED"}</div></div><div className="map"><MapContainer center={pos} zoom={15} scrollWheelZoom><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Center pos={pos}/>{child&&<Marker position={pos} icon={childIcon}><Popup><b>{child.name}</b><br/>Status: {child.status}<br/>Accuracy: {child.accuracy?Math.round(child.accuracy)+" m":"—"}</Popup></Marker>}{geo?.enabled&&<Circle center={[geo.latitude,geo.longitude]} radius={geo.radiusMeters} pathOptions={{className:"safe-circle"}}/>}</MapContainer></div></section><aside className="tracker-side"><section className={`status-card ${child?.status==="Safe"?"safe":"danger"}`}><div className="status-icon">{child?.status==="Safe"?<CheckCircle2/>:<AlertTriangle/>}</div><div><small>CHILD STATUS</small><h2>{child?.status||"Waiting"}</h2><span>{child?`${child.latitude.toFixed(5)}, ${child.longitude.toFixed(5)}`:"No GPS data"}</span></div></section><section className="panel"><Head title="Safe boundary" sub="Automatic geofence protection"/><label className="range">Radius <b>{radius} m</b><input type="range" min="50" max="2000" step="50" value={radius} onChange={e=>setRadius(e.target.value)}/></label><button className="btn primary full" onClick={saveGeo}><ShieldCheck/> Set boundary around child</button><div className="geo-detail"><span>Center</span><b>{geo?`${geo.latitude.toFixed(5)}, ${geo.longitude.toFixed(5)}`:"Not set"}</b></div></section><section className="panel"><Head title="GPS details" sub="Device telemetry"/><div className="telemetry"><div><small>Accuracy</small><b>{child?.accuracy?Math.round(child.accuracy)+" m":"—"}</b></div><div><small>Speed</small><b>{child?.speed?(child.speed*3.6).toFixed(1):"0"} km/h</b></div><div><small>Permission</small><b>{permission}</b></div><div><small>Alerts</small><b>{alerts.length}</b></div></div><button className="btn outline full" onClick={test}><Bell/> Send test alert</button></section></aside></div></>}
function Reports({reports,newReport}){return <><PageTitle eyebrow="SAFETY REPORTS" title="Safety reports" text="Document concerns so a responsible adult or safeguarding team can review them." action={<button className="btn primary" onClick={newReport}><Plus/> New report</button>}/><section className="panel">{reports.length?reports.map(r=><ReportRow key={r.id} r={r}/>):<Empty t="No safety reports yet."/>}</section></>}
function Contacts({contacts,add}){return <><PageTitle eyebrow="TRUSTED NETWORK" title="Trusted contacts" text="People who can support the child when help is needed." action={<button className="btn primary" onClick={add}><Plus/> Add contact</button>}/><div className="contact-grid">{contacts.map(c=><section className="panel contact" key={c.id}><div className="avatar">{c.name[0]}</div><div><h3>{c.name}</h3><p>{c.relation}</p><b>{c.phone}</b></div><a href={`tel:${c.phone}`} className="call"><Phone/></a></section>)}</div></>}
function Resources(){return <><PageTitle eyebrow="SAFETY RESOURCES" title="Practical safety guidance" text="Simple reminders for children, guardians, and trusted adults."/><div className="resource-grid">{resources.map(r=><section className="panel resource" key={r.title}><BookOpen/><h3>{r.title}</h3><p>{r.text}</p></section>)}</div></>}
function Activity({alerts}){if(!alerts.length)return <Empty t="No safety activity yet."/>;return <div className="activity">{alerts.map(a=><div className={`activity-row ${a.type==="GEOFENCE_EXIT"?"critical":""}`} key={a.id}><span>{a.type==="GEOFENCE_EXIT"?<AlertTriangle/>:<Bell/>}</span><div><b>{a.type==="GEOFENCE_EXIT"?"Safe boundary crossed":a.type==="SOS"?"SOS activated":"Safety notification"}</b><p>{a.message}</p></div><time>{time(a.createdAt)}</time></div>)}</div>}
function ReportRow({r}){return <div className="report-row"><span className={`tag ${r.urgency?.toLowerCase()}`}>{r.urgency}</span><div><b>{r.category}</b><p>{r.description}</p><small>{r.location} · {time(r.createdAt)}</small></div><span className="status-tag">{r.status}</span></div>}
function Stat({icon,value,label}){return <div className="stat"><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></div>}
function Quick({icon,t,s,on}){return <button className="quick" onClick={on}><span>{icon}</span><div><b>{t}</b><small>{s}</small></div><ChevronRight/></button>}
function Head({title,sub}){return <div className="head"><div><h2>{title}</h2><p>{sub}</p></div></div>}
function PageTitle({eyebrow,title,text,action}){return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Empty({t}){return <div className="empty"><ShieldCheck/><b>{t}</b></div>}
function ReportModal({close,submit}){const[f,setF]=useState({category:"General safety",description:"",location:"",urgency:"Medium"});return <Modal title="Report a safety concern" close={close}><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>General safety</option><option>Bullying</option><option>Online safety</option><option>Unsafe location</option><option>Other</option></select><textarea placeholder="Describe the concern…" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><input placeholder="Location (optional)" value={f.location} onChange={e=>setF({...f,location:e.target.value})}/><select value={f.urgency} onChange={e=>setF({...f,urgency:e.target.value})}><option>Low</option><option>Medium</option><option>High</option></select><button className="btn primary full" onClick={()=>submit(f)}>Submit report</button></Modal>}
function ContactModal({close,submit}){const[f,setF]=useState({name:"",relation:"",phone:""});return <Modal title="Add trusted contact" close={close}><input placeholder="Name" onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Relationship" onChange={e=>setF({...f,relation:e.target.value})}/><input placeholder="Phone number" onChange={e=>setF({...f,phone:e.target.value})}/><button className="btn primary full" onClick={()=>submit(f)}>Add contact</button></Modal>}
function SOS({close,confirm,contacts}){return <Modal title="SOS / Get Help" close={close}><div className="sos-box"><Siren/><b>Activate the guardian SOS workflow?</b><p>This records an SOS alert and can be connected to verified guardian/telephony services.</p></div><button className="btn emergency full" onClick={confirm}><Siren/> Activate SOS</button>{contacts[0]&&<a className="btn outline full" href={`tel:${contacts[0].phone}`}><Phone/> Call {contacts[0].name}</a>}</Modal>}
function Modal({title,close,children}){return <div className="overlay"><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}
